// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Donation Types
export const GET_DONATIONS = 'GET_DONATIONS';
export const GET_DONATION = 'GET_DONATION';
export const DONATION_ERROR = 'DONATION_ERROR';
export const CREATE_DONATION = 'CREATE_DONATION';

// Request Types
export const GET_REQUESTS = 'GET_REQUESTS';
export const GET_REQUEST = 'GET_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CREATE_REQUEST = 'CREATE_REQUEST';

// Feedback Types
export const GET_FEEDBACKS = 'GET_FEEDBACKS';
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';
export const CREATE_FEEDBACK = 'CREATE_FEEDBACK';

// Notification Types
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const GET_NOTIFICATION_COUNT = 'GET_NOTIFICATION_COUNT';

// Matching Types
export const GET_MATCHES = 'GET_MATCHES';
export const APPROVE_MATCH = 'APPROVE_MATCH';
export const MATCHING_ERROR = 'MATCHING_ERROR';
export const AUTO_MATCH_COMPLETE = 'AUTO_MATCH_COMPLETE';

// Logistics Types
export const GET_LOGISTICS = 'GET_LOGISTICS';
export const GET_LOGISTICS_ITEM = 'GET_LOGISTICS_ITEM';
export const CREATE_LOGISTICS = 'CREATE_LOGISTICS';
export const UPDATE_LOGISTICS = 'UPDATE_LOGISTICS';
export const DELETE_LOGISTICS = 'DELETE_LOGISTICS';
export const LOGISTICS_ERROR = 'LOGISTICS_ERROR';